---
title: "Testing_Graphs"
output: html_document
date: "2025-04-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#including sanjana's script here, and working on plotting things in the subsequent cells
library(ArchR)
library(Giotto)

addArchRGenome("hg38") 
addArchRThreads(threads = 16)

arrow_file <-"/projectnb/paxlab/carlos/ArchR_Gastric/ArrowFiles/D01942_NG05827.arrow"
position_files <- "/projectnb/paxlab/carlos/ArchR_Gastric/ArrowFiles/tissue_positions_list.csv"

# Load ArchR project
proj <- ArchRProject(ArrowFiles = arrow_file, outputDirectory = "ArchR_Output")

# Load spatial data
spatial_data <- fread(position_files)
setnames(spatial_data, old = c("V1", "V2", "V3", "V4", "V5", "V6"), 
         new = c("barcode", "in_tissue", "array_row", "array_col", "x_spatial", "y_spatial"))
run_id <- 'D01942_NG05827'
spatial_data[, barcode := paste0(run_id, "#", barcode, "-1")]
# Get on-tissue barcodes (16,314)
filtered_barcodes <- spatial_data[in_tissue == 1]$barcode

proj_filtered <- proj[proj$cellNames %in% filtered_barcodes]

# Get the gene score matrix
geneScoreMatrix <- getMatrixFromProject(proj_filtered, useMatrix = "GeneScoreMatrix")
genescore_matrix <- geneScoreMatrix@assays@data$GeneScoreMatrix

# Get gene names from annotations
gene_ano <- getGeneAnnotation(proj_filtered)
gene_ids <- gene_ano$genes$gene_id
gene_symbols <- gene_ano$genes$symbol

# Assign gene names to sparse matrix
rownames(genescore_matrix) <- rowData(geneScoreMatrix)$name 

proj_filtered <- addIterativeLSI( proj_filtered,
                                  name = "IterativeLSI",
                                  force = TRUE
)

proj_filtered <- addImputeWeights(
  ArchRProj = proj_filtered,
  reducedDims = "IterativeLSI"
)
## added this line
spatial_coords <- spatial_data[barcode %in% proj_filtered$cellNames, .(barcode, x_spatial, y_spatial)]

archrImputedMatrix <- imputeMatrix(
  mat = genescore_matrix,
  imputeWeights = getImputeWeights(proj_filtered)
)

giotto_obj <- createGiottoObject(
  expression = list(
    spatial_atac = list(
      raw = genescore_matrix,
      archr_imputed = archrImputedMatrix
    )
  ),
  spatial_locs = spatial_coords,
  instructions = createGiottoInstructions(python_path = NULL)
)
```
```{r}
# Lets compare the proj fragment sizes and the proj_filtered fragment sizes
p <- plotFragmentSizes(proj, returnDF = TRUE)
library(ggplot2)
p %>% ggplot(aes(fragmentSize, fragmentPercent)) + geom_line() + facet_wrap(~group)

```
```{r}
gg <- ggplot(data = p, aes(x = fragmentSize, y = fragmentPercent)) +
  geom_line() +
  facet_wrap(~group)

print(gg)

```

```{r}
p2 <- plotFragmentSizes(proj_filtered, returnDF = TRUE)

p2 %>% ggplot(aes(fragmentSize, fragmentPercent)) + geom_line() + facet_wrap(~group)
```
```{r}
gg2 <- ggplot(data = p2, aes(x = fragmentSize, y = fragmentPercent)) +
  geom_line() +
  facet_wrap(~group)

print(gg2)
```
```{r}
d <- plotTSSEnrichment(proj,returnDF = TRUE)
head(d)
```
```{r}
d2 <- plotTSSEnrichment(proj_filtered, returnDF = TRUE)
head(d2)
```

```{r}
library(ggplot2)

# Assuming your DataFrame is called `df`:
ggplot(d, aes(x = x, y = normValue, color = group)) +
  geom_line() +
  labs(
    title = "TSS Enrichment Profile - proj",
    x = "Distance from TSS (bp)",
    y = "Normalized TSS Enrichment"
  ) +
  theme_minimal()

```

```{r}
# Assuming your DataFrame is called `df`:
ggplot(d2, aes(x = x, y = normValue, color = group)) +
  geom_line() +
  labs(
    title = "TSS Enrichment Profil - prof_filtered",
    x = "Distance from TSS (bp)",
    y = "Normalized TSS Enrichment"
  ) +
  theme_minimal()
```
```{r}
d_ <- getCellColData(proj, select = c("TSSEnrichment", "nFrags")) %>% 
  as.data.frame() %>% 
  mutate(log10_nFrags = log10(nFrags))

```

```{r}
ggplot(d_, aes(x = log10_nFrags, y = TSSEnrichment)) +
  geom_point(alpha = 0.3, size = 0.5, color = "dodgerblue") +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", color = NA, alpha = 0.4) +
  geom_vline(xintercept = 3, linetype = "dashed") +
  geom_hline(yintercept = 10, linetype = "dashed") +
  scale_fill_viridis_c() +
  labs(
    title = "TSS Enrichment vs Log10 Unique Fragments",
    x = "Log10(Unique Fragments)",
    y = "TSS Enrichment"
  ) +
  theme_minimal()
```
```{r}

d2_ <- getCellColData(proj_filtered, select = c("TSSEnrichment", "nFrags")) %>% 
  as.data.frame() %>% 
  mutate(log10_nFrags = log10(nFrags))


```

```{r}
ggplot(d2_, aes(x = log10_nFrags, y = TSSEnrichment)) +
  geom_point(alpha = 0.3, size = 0.5, color = "dodgerblue") +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", color = NA, alpha = 0.4) +
  geom_vline(xintercept = 3, linetype = "dashed") +
  geom_hline(yintercept = 10, linetype = "dashed") +
  scale_fill_viridis_c() +
  labs(
    title = "TSS Enrichment vs Log10 Unique Fragments",
    x = "Log10(Unique Fragments)",
    y = "TSS Enrichment"
  ) +
  theme_minimal()
```




